<?php
$CFG->theme = "moove";
$CFG->themedesignermode = "0";
$CFG->auth = "none";
$CFG->authpreventaccountcreation = "0";
$CFG->enrol_plugins_enabled = "manual,guest,self,cohort,autoenrol";
$CFG->registerauth = "";
$CFG->defaulthomepage = "1";
$CFG->frontpage = "6";
$CFG->frontpagecourselimit = "200";
$CFG->frontpageloggedin = "6";
$CFG->forced_plugin_settings['auth_none'] = [
        'field_lock_address' => "locked",
        'field_lock_alternatename' => "locked",
        'field_lock_city' => "unlocked",
        'field_lock_country' => "unlocked",
        'field_lock_department' => "locked",
        'field_lock_description' => "unlocked",
        'field_lock_email' => "unlocked",
        'field_lock_firstname' => "unlocked",
        'field_lock_firstnamephonetic' => "locked",
        'field_lock_idnumber' => "locked",
        'field_lock_institution' => "locked",
        'field_lock_lang' => "unlocked",
        'field_lock_lastname' => "unlocked",
        'field_lock_lastnamephonetic' => "locked",
        'field_lock_middlename' => "locked",
        'field_lock_phone1' => "locked",
        'field_lock_phone2' => "locked",
];
$CFG->forced_plugin_settings['enrol_autoenrol'] = [
        'autounenrolaction' => "0",
        'availabilityplugins' => "grouping,profile",
        'defaultenrol' => "1",
        'defaultrole' => "5",
        'enrolperiod' => "0",
        'expiredaction' => "0",
        'expirynotify' => "0",
        'expirynotifyhour' => "6",
        'expirythreshold' => "86400",
        'loginenrol' => "1",
        'longtimenosee' => "0",
        'maxenrolled' => "0",
        'newenrols' => "1",
        'removegroups' => "1",
        'selfunenrol' => "1",
        'sendcoursewelcomemessage' => "0",
];
$CFG->forced_plugin_settings['theme_moove'] = [
        'logo' => $CFG->wwwroot . "/theme/moove/pix/UNODC_Logos.png",
        'favicon' => $CFG->wwwroot . "/theme/moove/pix/favicon.ico",
        'alertmsg' => "",
        'bannercontent' => "The unodcbox offers you the possibility to access high quality courses in areas with no or limited internet. ",
        'bannerheading' => "unodc in a box",
        'brandcolor' => "#5700c3",
        'clientscount' => "1",
        'clientsfrontpage' => "0",
        'clientsimage1' => "",
        'clientssubtitle' => "Clients that believe in us",
        'clientstitle' => "Our clients",
        'clientsurl1' => "",
        'courselistview' => "0",
        'coursepresentation' => "1",
        'disablefrontpageloginbox' => "0",
        'disableteacherspic' => "0",
        'displaymarketingbox' => "0",
        'facebook' => "",
        'forumcustomtemplate' => "0",
        'forumhtmlemailfooter' => "",
        'forumhtmlemailheader' => "",
        'getintouchcontent' => "",
        'googleanalytics' => "",
        'instagram' => "",
        'linkedin' => "",
        'loginbgimg' => "",
        'mail' => "",
        'mobile' => "",
        'navbarbg' => "#ff3b68",
        'navbarbghover' => "#ff3b68",
        'navbarheadercolor' => "",
        'numbersfrontpage' => "0",
        'preset' => "default.scss",
        'presetfiles' => "",
        'scss' => "",
        'scsspre' => "",
        'slidercap1' => "",
        'slidercount' => "1",
        'sliderenabled' => "0",
        'sliderfrontpage' => "0",
        'sliderimage1' => "",
        'slidertitle1' => "",
        'sponsorscount' => "1",
        'sponsorsfrontpage' => "0",
        'sponsorsimage1' => "",
        'sponsorssubtitle' => "",
        'sponsorstitle' => "",
        'sponsorsurl1' => "",
        'telegram' => "",
        'topfooterimg' => "",
        'twitter' => "",
        'website' => "",
        'whatsapp' => "",
        'youtube' => "",
];
$CFG->pathtodu = "/usr/bin/du";
$CFG->pathtogs = "/usr/bin/gs";
$CFG->pathtophp = "/usr/bin/php";
$CFG->pathtopython = "/usr/bin/python";

